web:
  build: .
  dockerfile: next/Dockerfile
  links:
    - db:db
    - cache:cache
  volumes:
    - ..:/code
    - ./virtualenvs:/home/invenio/.virtualenvs
  ports:
    - "8080:8080"

db:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ../data/mysql:/var/lib/mysql
  ports:
    - "3306:3306"

cache:
  image: redis
